/**
 * Default workspace profiles and typed signal events for PC and Snacks categories.
 * These are consumed by the scoring engine (scoringEngine.ts).
 */

import type { WorkspaceProfile, SignalEvent } from "./scoringEngine";

// ─── PC / LAPTOP SIGNAL EVENTS ───────────────────────────────────────────────

export const PC_SIGNAL_EVENTS: SignalEvent[] = [
  {
    id: "pc-1",
    title: "Microsoft launches Surface Pro 11 with OLED touchscreen targeting India enterprise",
    category: "product",
    geography: "India",
    channel: "Retail",
    actor: "Microsoft",
    eventType: "SKU launches",
    magnitude: 0.95,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-04-12"),
    description: "Surface Pro 11 features OLED display, Snapdragon X Elite, targeting enterprise and creator segment in India.",
  },
  {
    id: "pc-2",
    title: "Microsoft Azure AI bundling with Surface devices accelerates enterprise lock-in",
    category: "pricing",
    geography: "India",
    channel: "B2B",
    actor: "Microsoft",
    eventType: "Bundle / multi-pack offers",
    magnitude: 0.85,
    sourceConfidence: 0.75,
    isDirectlyVerifiable: false,
    timestamp: new Date("2026-03-15"),
    description: "Microsoft bundling Azure AI credits with Surface enterprise purchases, creating pricing advantage and ecosystem lock-in.",
  },
  {
    id: "pc-3",
    title: "Dell XPS 13 Touch secures exclusive retail placement in Reliance Digital outlets",
    category: "distribution",
    geography: "India",
    channel: "Retail",
    actor: "Dell",
    eventType: "Exclusive partnership announcements",
    magnitude: 0.85,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-04-09"),
    description: "Dell signs exclusive placement agreement with Reliance Digital for XPS 13 Touch, securing premium shelf space in 200+ outlets.",
  },
  {
    id: "pc-4",
    title: "Samsung Galaxy Book4 Edge launches with Snapdragon X Elite chipset in APAC",
    category: "product",
    geography: "Asia Pacific",
    channel: "Retail",
    actor: "Samsung",
    eventType: "SKU launches",
    magnitude: 0.75,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-03-24"),
    description: "Samsung Galaxy Book4 Edge ARM-based touchscreen laptop competing in the premium ultrabook space.",
  },
  {
    id: "pc-5",
    title: "ASUS ROG Flow Z13 launches with 30% lower price targeting creator segment",
    category: "pricing",
    geography: "India",
    channel: "Retail",
    actor: "ASUS",
    eventType: "List price changes",
    magnitude: 0.70,
    sourceConfidence: 0.82,
    isDirectlyVerifiable: false,
    timestamp: new Date("2026-04-06"),
    description: "ASUS re-prices ROG Flow Z13 touchscreen laptop 30% below previous gen, targeting creator professionals.",
  },
  {
    id: "pc-6",
    title: "HP Spectre x360 wins top touchscreen review score across APAC tech publications",
    category: "positioning",
    geography: "Asia Pacific",
    channel: "Retail",
    actor: "HP",
    eventType: "Brand repositioning signals",
    magnitude: 0.65,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-04-02"),
    description: "HP Spectre x360 receives top creator/productivity benchmark scores across major APAC tech outlets.",
  },
  {
    id: "pc-7",
    title: "Lenovo Yoga 9i enterprise refresh closes 18 new B2B procurement deals in Q1",
    category: "org",
    geography: "India",
    channel: "B2B",
    actor: "Lenovo",
    eventType: "Team expansions in R&D / Sales",
    magnitude: 0.60,
    sourceConfidence: 0.90,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-03-28"),
    description: "Lenovo enterprise team secures 18 new B2B procurement deals for Yoga 9i in Q1 2026.",
  },
  {
    id: "pc-8",
    title: "Acer Aspire Vero 16 Touch targets sustainability-conscious enterprise buyers",
    category: "positioning",
    geography: "India",
    channel: "B2B",
    actor: "Acer",
    eventType: "Campaign launches",
    magnitude: 0.45,
    sourceConfidence: 0.65,
    isDirectlyVerifiable: false,
    timestamp: new Date("2026-03-20"),
    description: "Acer launches sustainability-focused campaign for Aspire Vero 16 Touch targeting ESG-conscious enterprise procurement.",
  },
];

// ─── SNACKS SIGNAL EVENTS ─────────────────────────────────────────────────────

export const SNACKS_SIGNAL_EVENTS: SignalEvent[] = [
  {
    id: "snacks-1",
    title: "Pepsi launches low-sugar Lays variant in India",
    category: "product",
    geography: "India",
    channel: "Modern Trade",
    actor: "Pepsi",
    eventType: "SKU launches",
    magnitude: 0.90,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-04-10"),
    description: "Pepsi introduces low-sugar Lays targeting health-conscious millennials in Tier 1 cities.",
  },
  {
    id: "snacks-2",
    title: "Nestlé files clean-label reformulation patent (IN-2026-04821)",
    category: "formulation",
    geography: "India",
    channel: "Modern Trade",
    actor: "Nestlé",
    eventType: "Patent filings",
    magnitude: 0.80,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-04-03"),
    description: "Nestlé files patent for clean-label cracker reformulation removing artificial preservatives.",
  },
  {
    id: "snacks-3",
    title: "ITC increases promotional frequency in premium snacks Q2",
    category: "pricing",
    geography: "India",
    channel: "Modern Trade",
    actor: "ITC",
    eventType: "Promotional mechanics",
    magnitude: 0.75,
    sourceConfidence: 0.75,
    isDirectlyVerifiable: false,
    timestamp: new Date("2026-04-08"),
    description: "ITC running 40% more promotional activities in premium snack segment vs Q1.",
  },
  {
    id: "snacks-4",
    title: "Mondelez shifts APAC messaging to 'natural ingredients'",
    category: "positioning",
    geography: "India",
    channel: "Modern Trade",
    actor: "Mondelez",
    eventType: "Claim changes or additions",
    magnitude: 0.70,
    sourceConfidence: 0.68,
    isDirectlyVerifiable: false,
    timestamp: new Date("2026-03-30"),
    description: "Mondelez repositioning APAC portfolio around natural ingredients narrative.",
  },
  {
    id: "snacks-5",
    title: "Hershey R&D team expansion — 14 new hires in innovation",
    category: "org",
    geography: "India",
    channel: "Modern Trade",
    actor: "Hershey",
    eventType: "Team expansions in R&D / Sales",
    magnitude: 0.60,
    sourceConfidence: 0.92,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-04-05"),
    description: "Hershey expanding R&D team with 14 new hires focused on health-oriented innovation.",
  },
  {
    id: "snacks-6",
    title: "Britannia launches rice cracker variant targeting premium segment",
    category: "product",
    geography: "India",
    channel: "Modern Trade",
    actor: "Britannia",
    eventType: "SKU launches",
    magnitude: 0.80,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-03-28"),
    description: "Britannia premium rice cracker variant launched in 100g and 200g packs.",
  },
  {
    id: "snacks-7",
    title: "Parle introduces biodegradable packaging across select SKUs",
    category: "packaging",
    geography: "India",
    channel: "General Trade",
    actor: "Parle",
    eventType: "Sustainable material switches",
    magnitude: 0.55,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-03-25"),
    description: "Parle switches to biodegradable packaging for 5 SKUs as part of sustainability initiative.",
  },
  {
    id: "snacks-8",
    title: "ITC signs exclusive partnership with Reliance Retail for premium shelf placement",
    category: "distribution",
    geography: "India",
    channel: "Modern Trade",
    actor: "ITC",
    eventType: "Exclusive partnership announcements",
    magnitude: 0.90,
    sourceConfidence: 1.0,
    isDirectlyVerifiable: true,
    timestamp: new Date("2026-03-22"),
    description: "ITC secures exclusive premium shelf placement agreement with Reliance Retail.",
  },
];

// ─── PC WORKSPACE PROFILE ────────────────────────────────────────────────────

export const PC_WORKSPACE: WorkspaceProfile = {
  categories: ["product", "digital", "pricing", "distribution", "positioning", "org"],
  markets: ["India", "South Asia", "Asia Pacific"],
  channels: ["Retail", "E-commerce", "B2B", "Enterprise"],
  competitors: [
    { name: "Microsoft", tier: "primary" },
    { name: "Dell",      tier: "primary" },
    { name: "ASUS",      tier: "secondary" },
    { name: "HP",        tier: "secondary" },
    { name: "Lenovo",    tier: "secondary" },
    { name: "Samsung",   tier: "secondary" },
    { name: "Acer",      tier: "secondary" },
  ],
  minScopeThreshold: 0.35,
  alertThreshold: 50,
  positioning:
    "Premium touchscreen laptops built for creators and enterprise professionals — performance, display quality, and cross-platform ecosystem independence",
  consumerProfiles: [
    "Creator Professionals",
    "Enterprise IT Buyers",
    "Remote Working Professionals",
  ],
  vulnerabilities: [
    "OLED display gap vs Microsoft Surface",
    "Microsoft ecosystem lock-in risk",
    "Retail distribution disadvantage",
  ],
  intents: [
    "Defend premium touchscreen segment",
    "Expand enterprise presence in India",
  ],
  capabilities: {
    product:      0.80,
    pricing:      0.75,
    messaging:    0.85,
    distribution: 0.70,
  },
  revenueShare: {
    India:          0.40,
    "South Asia":   0.15,
    "Asia Pacific": 0.25,
  },
  eventHistory: PC_SIGNAL_EVENTS,
};

// ─── SNACKS WORKSPACE PROFILE ────────────────────────────────────────────────

export const SNACKS_WORKSPACE: WorkspaceProfile = {
  categories: ["product", "pricing", "positioning", "formulation", "distribution", "packaging", "org", "claims"],
  markets: ["India", "South Asia"],
  channels: ["Modern Trade", "General Trade", "E-commerce"],
  competitors: [
    { name: "Pepsi",    tier: "primary" },
    { name: "ITC",      tier: "primary" },
    { name: "Nestlé",   tier: "secondary" },
    { name: "Hershey",  tier: "secondary" },
    { name: "Mondelez", tier: "secondary" },
    { name: "Britannia",tier: "secondary" },
    { name: "Parle",    tier: "secondary" },
  ],
  minScopeThreshold: 0.35,
  alertThreshold: 50,
  positioning:
    "Premium indulgence with healthier perception — clean ingredients, bold taste, trusted brand for health-conscious consumers",
  consumerProfiles: [
    "Health-conscious Millennials",
    "Budget-conscious Families",
    "Premium-seeking Gen X",
  ],
  vulnerabilities: [
    "Premium pricing risk",
    "Weak health positioning vs competitors",
  ],
  intents: [
    "Defend premium positioning",
    "Expand into health segment",
  ],
  capabilities: {
    product:      0.80,
    pricing:      0.85,
    messaging:    0.80,
    distribution: 0.75,
  },
  revenueShare: {
    India:        0.65,
    "South Asia": 0.25,
  },
  eventHistory: SNACKS_SIGNAL_EVENTS,
};
